services:
  postgres:
    image: postgres:13
    container_name: better-analytics-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: better-analytics
    ports:
      - "5433:5432"
    volumes:
      - better_analytics_postgres_data:/var/lib/postgresql/data

volumes:
  better_analytics_postgres_data: