ALTER TABLE "events" ADD COLUMN "userAgent" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "browser" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "os" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "device" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "deviceVendor" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "deviceModel" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "engine" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "cpu" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "country" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "region" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "city" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "sessionId" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "userId" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "pageTitle" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "pathname" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "hostname" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "loadTime" integer;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "utmSource" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "utmMedium" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "utmCampaign" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "utmTerm" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "utmContent" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "screenWidth" integer;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "screenHeight" integer;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "viewportWidth" integer;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "viewportHeight" integer;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "language" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "createdAt" timestamp DEFAULT now();